### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by Schnurber** [flame-engine/play_games#2]
Hi, there is a note:
`xyz/luan/games/play/playgames/Request.java uses or overrides a deprecated API.`
And a message:
`I/xyz.luan.games.play.playgames.PlayGamesPlugin(16663): Failed to silent signin, trying explicit signin`
The example application does not work either.

**Comment by luanpotter** [comment]
Hi, @oth-aw ! Have you followed the lengthy tutorial that I provided explaining how to setup everything? It's very hard to configure everything.

Please take a look [here](https://github.com/luanpotter/play_games/blob/master/doc/signin.md).

**Comment by Schnurber** [comment]
Hi Yes I did. The setup is OK I guess. The test of the connection (with firebase console) was successful. I'm at a loss.

**Comment by Jhon2524** [comment]
Same error, any news ?

`I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): Failed to silent signin, trying explicit signin
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): com.google.android.gms.common.api.ApiException: 4: 4: 
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at com.google.android.gms.common.internal.zai.zaf(com.google.android.gms:play-services-base@@17.1.0:2)
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at com.google.android.gms.common.internal.zak.onComplete(com.google.android.gms:play-services-base@@17.1.0:6)
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at com.google.android.gms.common.api.internal.BasePendingResult.zaa(com.google.android.gms:play-services-base@@17.1.0:176)
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.1.0:135)
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at com.google.android.gms.auth.api.signin.internal.zzi.zzc(com.google.android.gms:play-services-auth@@18.1.0:5)
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at com.google.android.gms.auth.api.signin.internal.zzs.zzc(com.google.android.gms:play-services-auth@@18.1.0:6)
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at com.google.android.gms.internal.auth-api.zzc.onTransact(com.google.android.gms:play-services-auth@@18.1.0:13)
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): 	at android.os.Binder.execTransact(Binder.java:994)
W/ActivityThread(27003): handleWindowVisibility: no activity for token android.os.BinderProxy@4fd66b7
I/flutter (27003): ERROR Unexpected error Status{statusCode=unknown status code: 12501, resolution=null}`

**Comment by luanpotter** [comment]
`xyz/luan/games/play/playgames/Request.java uses or overrides a deprecated API.` is unrelated btw, that is just a warning.

**Comment by luanpotter** [comment]
Have you tried the solution on https://github.com/flame-engine/play_games/issues/7 ? Might be the same issue
