### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Jhon2524** [flame-engine/play_games#21]
I followed all the instructions.

Updated the manifest, connected my app to firebase,
linked and updated sha1 and sha256,
added test device,
requested authorization and updated the onauth screen from the google console api,
despite that I still have this annoying error 👍

`I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): Failed to silent signin, trying explicit signin I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): com.google.android.gms.common.api.ApiException: 4: 4: I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.internal.zai.zaf(com.google.android.gms:play-services-base@@17.1.0:2) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.internal.zak.onComplete(com.google.android.gms:play-services-base@@17.1.0:6) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.api.internal.BasePendingResult.zaa(com.google.android.gms:play-services-base@@17.1.0:176) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.1.0:135) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.auth.api.signin.internal.zzi.zzc(com.google.android.gms:play-services-auth@@18.1.0:5) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.auth.api.signin.internal.zzs.zzc(com.google.android.gms:play-services-auth@@18.1.0:6) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.internal.auth-api.zzc.onTransact(com.google.android.gms:play-services-auth@@18.1.0:13) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at android.os.Binder.execTransactInternal(Binder.java:1021) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at android.os.Binder.execTransact(Binder.java:994) W/ActivityThread(27003): handleWindowVisibility: no activity for token android.os.BinderProxy@4fd66b7 I/flutter (27003): ERROR Unexpected error Status{statusCode=unknown status code: 12501, resolution=null}`

anyone else in my situation?
thanks

**Comment by luanpotter** [comment]
Closing in lieu of #2
