### ISSUE TITLE
Error while signing in

### ISSUE THREAD

**Issue by chaitu750** [flame-engine/play_games#22]
Hi,
I am getting following error while trying to signing in
[VERBOSE-2:ui_dart_state.cc(177)]  Unhandled Exception: type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:41)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:340:12)
#2      PlayGames.signIn (package:play_games/play_games.dart:338:54)

**Comment by luanpotter** [comment]
1. please format your code/logs correctly
2. what platform? device or emulator?
3. sample code that you are using?
